//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodB_MAUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PodB_MAUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string add_item_page_title {
            get {
                return ResourceManager.GetString("add_item_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string Add_Item_Title {
            get {
                return ResourceManager.GetString("Add_Item_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery Store System.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string lbl_product_category {
            get {
                return ResourceManager.GetString("lbl_product_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string lbl_product_description {
            get {
                return ResourceManager.GetString("lbl_product_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name:.
        /// </summary>
        internal static string lbl_product_name {
            get {
                return ResourceManager.GetString("lbl_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo URL:.
        /// </summary>
        internal static string lbl_product_photo_url {
            get {
                return ResourceManager.GetString("lbl_product_photo_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Link:.
        /// </summary>
        internal static string lbl_product_picture {
            get {
                return ResourceManager.GetString("lbl_product_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ph_product_category {
            get {
                return ResourceManager.GetString("ph_product_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ph_product_description {
            get {
                return ResourceManager.GetString("ph_product_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        internal static string ph_product_name {
            get {
                return ResourceManager.GetString("ph_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo URL.
        /// </summary>
        internal static string ph_product_photo_url {
            get {
                return ResourceManager.GetString("ph_product_photo_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ph_product_price {
            get {
                return ResourceManager.GetString("ph_product_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Type.
        /// </summary>
        internal static string ph_quantity_type {
            get {
                return ResourceManager.GetString("ph_quantity_type", resourceCulture);
            }
        }
    }
}
